apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: httpd
        image: ashok77jayaraman/pr2
        ports:
        - containerPort: 80
